department-of-veterans-affairs/ves-event-bus-developer-portal

catalog-info.yaml

Mc 678 kind research

---

docs/get-support.md
docs/support/get-support.md
mkdocs.yml

This PR updates the contents of gets-support page in our dev portal
It also moves it one level up in the navigation bar
https://github.com/department-of-veterans-affairs/VES/issues/562

Docs: Update get-support information

---

docs/offboard.md
mkdocs.yml

https://github.com/department-of-veterans-affairs/VES/issues/561#event-9680195689
Adds Offboard content to our Portal

Docs: Add Offboard content

---

docs/README.md
docs/consume-events.md
docs/produce-events.md

- Added Brian's new sample code from the [ves-event-bus-sample-code](https://github.com/department-of-veterans-affairs/ves-event-bus-sample-code) repo and replaced the warnings with a link to the repo for full context.
- Added a link to the video + slide deck to to the homepage
- Other misc. fixes (sorry about the spacing changes)

Add  new sample code + homepage update

---

docs/consume-events.md
docs/produce-events.md

Small fix to reflect the naming change decided on in the 8/14 mob session.

Update link to sample code

---

docs/README.md
docs/get-started.md

Link changed due to GitHub doc repo updates.

Fix broken slide deck link

---

docs/produce-events.md

Add documentation about Backstage links to Event Producer documentation

1534 - add documentation about Backstage links

---

docs/consume-events.md

Switch "producers" to "consumers" in consumer authorization and authentication documentation

1853 - Small fix in consumer authorization documentation

---

.gitignore
docs/environments.md
mkdocs.yml

This document describes the deployment environments. We still need to decide where to link to it from other pages.

Add environments description page.

---

README.md

3361 - update readme

---

docs/produce-events.md

Add `removalDate` property to CODE VA instructions for event producers.

1087 - add removalDate to producer catalog-info.yaml instructions

---

README.md
mkdocs.yml

This PR removes search functionality from the developer portal. Also added a note to the README about this.

3511 - turn off search functionality

---

.github/pull_request_template.md

This PR adds a PR template to this repository.
Unable to test at the moment, but once the template is merged in I will test by starting the process of opening a PR.

3948 - Add PR template

---

docs/intro-to-eda.md

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4228
- Adds _ New copy to Event driver architecture page
- Fixes _ N/A
- I tested these changes by _ Viewing locally

Changes to Event Driven Architecture page

---

docs/administrative-requirements.md

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4229
- Adds _ Layout and copy changes
- Fixes _ N/A
- I tested these changes by _ Running locally and verifying against[ admin requirements google doc ](https://docs.google.com/document/d/10sRl8hkBusS-rwY2eC42HlU5vlG3TYZcJ7jqquWzoFc/edit?tab=t.0)

Made layout and copy changes to the administrative requirements page

---

docs/administrative-requirements.md

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4229
- Adds _ New heading, title update
- Fixes _ N/A
- I tested these changes by _ Running and viewing site locally

4229 update admin page, title, sub-heading

---

docs/README.md

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4227
- Adds _ New heading to event bus workflow example image
- Fixes _ N/A
- I tested these changes by _ Running locally

Added heading and spacing to event bus workflow example image

---

mkdocs.yml

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4230
- Adds _ Combines right and left navigation menus into a single one on the left of the screen.
- Fixes _ N/A
- I tested these changes by _ Running site locally

Updates navigation

---

docs/README.md
docs/administrative-requirements.md
docs/consume-events.md
docs/environments.md
docs/get-support.md
docs/intro-to-eda.md
docs/offboard.md
docs/produce-events.md
docs/terminology.md
docs/use-events.md

Resolves https://github.com/department-of-veterans-affairs/ves/issues/4559
- Adds _ bolded headings
- Fixes _ changed headers to bolded
- I tested these changes by looking at the preview

Jacq bolded headers on the dev portal homepage

---

docs/consume-events.md
docs/intro-to-eda.md
docs/produce-events.md

Resolves https://github.com/department-of-veterans-affairs/ves/issues/4714
- Adds _ new sections and images as needed
- Fixes _ links and verbiage
- I tested these changes by looking at the preview

Updating Event Driven Architecture, Consumer, and Producer pages

---

docs/produce-events.md

Resolves https://github.com/department-of-veterans-affairs/VES/issues/4761
- Adds _ Additional line of guidance for USE_SCHEMA_ID
- Fixes _ N/A
- I tested these changes by _ Running locally and verifying correct look.

Updated guidence for USE_SCHEMA_ID

---

docs/README.md

Resolves https://github.com/department-of-veterans-affairs/ves/issues/4556
- Adds New content for non-technical users. New diagrams.
- Fixes Old content that is not compelling.
- I tested these changes by looking at the preview

Updates to homepage

---

docs/README.md

Resolves https://github.com/department-of-veterans-affairs/ves/issues/4556
- Adds _ NA
- Fixes _ Weird bullet spacing
- I tested these changes by checking the preview

Update to homepage
